### ISSUE TITLE
当前存在的bug或实现较弱的地方

### ISSUE THREAD

**Issue by drityddv** [drityddv/miniServer#52]
1. 地图没有心跳机制 玩家登出接口netty也会调用,为了地图的重连支持,应该在地图加上心跳
2. 背包的机制遍历太多,实现也较弱.
3. 战斗属性容器和玩家容器暂时没有分开处理.
4. 背包旧的数量机制没有改的地方需要改掉.

**Comment by vilinian** [comment]
背包的实现好好梳理下, 细节也要注意下

**Comment by drityddv** [comment]
目前只剩3没有处理
